% Set fixed point arithmetic rule
F = fimath('OverflowAction', 'Saturate', 'RoundingMethod', 'Nearest', ...
    'ProductMode', 'SpecifyPrecision', 'ProductFractionLength', fl, ...
    'ProductWordLength', wl, 'SumMode', 'SpecifyPrecision', ...
    'SumFractionLength', fl, 'SumWordLength', wl);
% Set fixed point data type
T = numerictype('WordLength', wl, 'FractionLength', fl, 'Signed', 1);